### PR TITLE
Workaround for Cannot read property 'contents' of undefined

### PR DESCRIPTION
**Pull request by psergei**
Easy workaround for issue https://github.com/gruntjs/grunt-contrib-imagemin/issues/325

### CODE REVIEW

**Comment by vladikoff** [comment]
Should be fixed via https://github.com/gruntjs/grunt-contrib-imagemin/pull/329

**Comment by psergei** [comment]
Yes, thanks, Forcing 4.0.0 imagemin package for grunt-contrib-imagemin works.

**Comment by vladikoff** [comment]
Yay!

**Comment by Darvile** [comment]
#329 did the trick form me

**Pull request closed without merging**
