### PR TITLE
Security Audit Fixes

### PR DESCRIPTION
**Pull request by whyisjake**
As part of a security audit, would like to upstream these changes into `grunt-contrib-imagemin`.

### CODE REVIEW

**Comment by whyisjake** [comment]
This is a fix for #391

**Comment by whyisjake** [comment]
WordPress core issue here: https://core.trac.wordpress.org/ticket/49547#comment:4

**Comment by whyisjake** [comment]
@sindresorhus, @kevva, @XhmikosR, or @vladikoff any ideas on how to get this merged/released?

**Comment by vladikoff** [comment]
I can take a look...

**Comment by XhmikosR** [comment]
For what is worth, there's no fix for the latest decompress  AFAICT. That being said, this can land since tests pass, and even be more updated later and drop Node < 10 support.

**Comment by whyisjake** [comment]
Cool, can we get a :shipit: then?

**Pull request merged**
