### PR TITLE
Update imagemin to 4.0.0

### LINKED ISSUE #325: Cannot read property 'contents' of undefined
Hi, I cannot figure out what is happening here, and how to fix it. When I run `grunt imagemin -vd --stack`

I get that : 

        Options: interlaced, optimizationLevel=3, progressive, cache=false
	Fatal error: Cannot read property 'contents' of undefined
	TypeError: Cannot read property 'contents' of undefined
	    at /home/cyril/dev/workspace/client/node_modules/grunt-contrib-imagemin/tasks/imagemin.js:61:54
	    at ConcatStream.<anonymous> (/home/cyril/dev/workspace/client/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/concat-stream/index.js:36:43)
	    at ConcatStream.emit (events.js:129:20)
	    at finishMaybe (/home/cyril/dev/workspace/client/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:502:14)
	    at endWritable (/home/cyril/dev/workspace/client/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:512:3)
	    at ConcatStream.Writable.end (/home/cyril/dev/workspace/client/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:477:5)
	    at DuplexWrapper.onend (/home/cyril/dev/workspace/client/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/readable-stream/lib/_stream_readable.js:539:10)
	    at DuplexWrapper.g (events.js:199:16)
	    at DuplexWrapper.emit (events.js:129:20)
	    at endReadableNT (/home/cyril/dev/workspace/client/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/readable-stream/lib/_stream_readable.js:944:12)
	    at afterTick (/home/cyril/dev/workspace/client/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/readable-stream/node_modules/process-nextick-args/index.js:11:8)
	    at process._tickCallback (node.js:355:11)
 

Could you help me please ?
 
my config is : 

     grunt-contrib-imagemin : 0.9.4
     imagemin : 3.2.0

and in Gruntfile.js : 

     imagemin: {
	  dist: {
	    options: {
	      cache:false
	    },
	    files: [{
	      expand: true,
	      cwd: '<%= yeoman.app %>/assets',
	      src: ['**/*.{png,jpg,jpeg,gif}'],
	      dest: '<%= yeoman.dist %>/assets'
	    }]
	  }
	},

### PR DESCRIPTION
**Pull request by sapegin**
Fixes #325 for me.

### CODE REVIEW

**Comment by zertosh** [comment]
Yes, this updated version of imagemin uses an updated version of vinyl-fs, that no longer relies on a bug in duplexer2. See https://github.com/deoxxa/duplexer2/commit/8fac12bb57d53f47d8dd7b16ca11079501bbe790#commitcomment-14269090

**Comment by Chexpir** [comment]
I need this fix soon! please!

**Comment by mbrainiac** [comment]
+1

**Comment by jpbackman** [comment]
+1

**Comment by jcampalo** [comment]
+1

**Comment by martinpesout** [comment]
+1

**Comment by errok** [comment]
+1

**Comment by thaiphv** [comment]
1+

**Comment by vysinsky** [comment]
:+1:

**Comment by vvanscherpenseel** [comment]
+1

**Comment by DanoDavid** [comment]
+1

**Comment by isrob** [comment]
+1

**Comment by larslaade** [comment]
+1

**Comment by iamfrontender** [comment]
+1

**Comment by joaovieira** [comment]
+1

**Comment by NomadeLampe** [comment]
+1

**Comment by sapegin** [comment]
Please don’t spam me with your plusones.

**Comment by domis86** [comment]
+1

**Comment by DrEnter** [comment]
+1

**Comment by joshlasdin** [comment]
+1

**Comment by shinnn** [comment]
ping @XhmikosR @vladikoff @sindresorhus @kevva

**Comment by vladikoff** [comment]
@_@

**Comment by AAudusseau** [comment]
+1

**Comment by jorrit** [comment]
This PR should be closed, it has been merged.

**Pull request merged**
